### ISSUE TITLE
Closing keyboard using OS back button does not hide action bar but only keyboard

### ISSUE THREAD

**Issue by krishnajithapa** [diegoveloper/flutter_keyboard_actions#207]
When user click on OS default back button, action bar is still visible although the keyboard hides

**Comment by diegoveloper** [comment]
Can you add a minimum code to reproduce the issue?
Also can you reproduce the issue using the samples from this repo?

**Comment by krishnajithapa** [comment]
you can try it on your sample code in your repo as well
Steps to reproduce:
1. Go to full screen form 
1. Tap on textformfield and wait for keyboard and action bar to appear.
2. press OS back button
 you will see the action bar doesnt disappear with keyboard

**Comment by diegoveloper** [comment]
can you give me more info?

- flutter version?
- android OS version?
- android device brand/model

**Comment by krishnajithapa** [comment]
flutter 3.3.2
android version: 11
device: pixel 3a

**Comment by diegoveloper** [comment]
Can you try using this PR (pointing to his repository)
https://github.com/diegoveloper/flutter_keyboard_actions/pull/208

Let me know if that fixes the issue.

**Comment by krishnajithapa** [comment]
I am currently at my office working on several projects so i don't think i will have enough spare time to perform the test myself any soon. Would appreciate if you could test and update the package accordingly.

**Comment by diegoveloper** [comment]
Fixed on this version `4.1.0` . https://github.com/diegoveloper/flutter_keyboard_actions/pull/208

**Comment by abeerrizvi** [comment]
The issue is still reproducible for iOS on 4.1.0.

If we hide the keyboard by using the SystemChannels `SystemChannels.textInput.invokeMethod('TextInput.hide')` actions gets hidden on android but on iOS they are still visible.

https://user-images.githubusercontent.com/110096395/213646557-bcc163d7-83d3-4f35-8f7f-260b629883e0.mp4


https://user-images.githubusercontent.com/110096395/213646575-cc6be3cb-a8bf-42bf-94e8-6d3c6eb35fa1.mp4

**Comment by zigapovhe** [comment]
@diegoveloper This bug still exists. What is this issue closed? On android, if you close the keyboard with an arrow, action bar stays visible. 
![signal-2023-04-17-111345_002](https://user-images.githubusercontent.com/21365070/232442671-17e6a65d-36bd-4f88-92dc-b9fc9c6aaf59.png)

**Comment by diegoveloper** [comment]
Can you add the minimal code to reproduce the issue?

**Comment by zigapovhe** [comment]
@diegoveloper I've used example from your repo. Didn't changed anything
